# Generated by Django 4.2.7 on 2023-11-05 09:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_contact_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
